# Generated by Django 5.1.2 on 2026-06-22 11:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SidebarMenuItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("href", models.CharField(max_length=200)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Lucide icon name, used when no image is uploaded.",
                        max_length=50,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="sidebar_icons/"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sidebar Menu Item",
                "verbose_name_plural": "Sidebar Menu Items",
                "db_table": "sidebar_menu_item",
                "ordering": ["order", "label"],
            },
        ),
    ]
