# Generated by Django 5.1.2 on 2026-06-22 11:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_admin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppLogo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="app_logo/")),
                ("alt", models.CharField(blank=True, default="配布館", max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "App Logo",
                "verbose_name_plural": "App Logo",
                "db_table": "app_logo",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="sidebarmenuitem",
            name="link_type",
            field=models.CharField(
                choices=[("menu", "Menu"), ("text", "Text link")],
                default="menu",
                max_length=10,
            ),
        ),
    ]
