# Generated by Django 5.1.2 on 2026-06-23 12:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_admin", "0002_applogo_sidebarmenuitem_link_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaqItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("category", models.CharField(blank=True, default="", max_length=100)),
                ("question", models.CharField(blank=True, default="", max_length=500)),
                ("answer", models.TextField(blank=True, default="")),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "FAQ Item",
                "verbose_name_plural": "FAQ Items",
                "db_table": "faq_item",
                "ordering": ["order", "category", "question"],
            },
        ),
    ]
