# Generated by Django 5.1.2 on 2026-06-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("client", "Client"),
                    ("distributor", "Distributor"),
                    ("author", "Author"),
                    ("manager", "Manager"),
                ],
                max_length=20,
            ),
        ),
    ]
