# Generated by Django 5.1.2 on 2026-06-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_userprofile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="registration_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
