# Generated by Django 5.1.2 on 2026-06-23 12:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AreaPrefecture",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("name_en", models.CharField(blank=True, max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Area Prefecture",
                "verbose_name_plural": "Area Prefectures",
                "db_table": "area_prefecture",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AreaCity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("name_en", models.CharField(blank=True, max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prefecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="core.areaprefecture",
                    ),
                ),
            ],
            options={
                "verbose_name": "Area City",
                "verbose_name_plural": "Area Cities",
                "db_table": "area_city",
                "ordering": ["prefecture__name", "name"],
                "unique_together": {("prefecture", "name")},
            },
        ),
        migrations.CreateModel(
            name="AreaPlace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("name_en", models.CharField(blank=True, max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=120)),
                ("total_households", models.PositiveIntegerField(default=0)),
                ("collective_households", models.PositiveIntegerField(default=0)),
                ("detached_households", models.PositiveIntegerField(default=0)),
                ("distance_m", models.PositiveIntegerField(default=0)),
                ("duration_minutes", models.PositiveIntegerField(default=0)),
                (
                    "duration_minutes_alt",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("estimated_price_yen", models.PositiveIntegerField(default=0)),
                (
                    "estimated_price_yen_alt",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "unit_price_yen",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "unit_price_yen_alt",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="places",
                        to="core.areacity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Area Place",
                "verbose_name_plural": "Area Places",
                "db_table": "area_place",
                "ordering": ["city__name", "name"],
                "unique_together": {("city", "name")},
            },
        ),
    ]
