# Generated by Django 5.1.2 on 2026-06-24 08:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProhibitedProperty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("tag_name", models.CharField(blank=True, max_length=255)),
                (
                    "impression",
                    models.CharField(
                        choices=[("kind", "優しい"), ("usual", "普通"), ("scared", "怖い")],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prohibited_properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Prohibited Property",
                "verbose_name_plural": "Prohibited Properties",
                "db_table": "prohibited_property",
                "ordering": ["-created_at"],
            },
        ),
    ]
