# Generated by Django 5.1.2 on 2026-06-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_prohibitedproperty"),
    ]

    operations = [
        migrations.AddField(
            model_name="areacity",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="areacity",
            name="number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="areacity",
            name="unique_id",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name="areaplace",
            name="details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="areaplace",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="areaplace",
            name="map_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="areaplace",
            name="number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="areaplace",
            name="unique_id",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name="areaprefecture",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
