# Generated by Django 5.1.2 on 2026-06-24 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_areacity_is_active_areacity_number_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="areaplace",
            unique_together=set(),
        ),
    ]
