# Generated by Django 5.1.2 on 2026-06-23 12:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("distribution_center", "配布館に関して"),
                            ("posting", "ポスティングに関して"),
                            ("flyer_info", "チラシ情報提供"),
                            ("flyer_protest", "チラシ配布に対する抗議"),
                        ],
                        max_length=50,
                    ),
                ),
                ("content", models.TextField(blank=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="inquiries/"),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("is_submitted", models.BooleanField(default=False)),
                (
                    "verification_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Inquiries",
                "db_table": "misc_inquiry",
                "ordering": ["-created_at"],
            },
        ),
    ]
